name: htw
version: 0.1.0.0
github: "githubuser/htw"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2021 Author name here"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/htw#readme>

dependencies:
  - base >= 4.7 && < 5
  - bytestring ==0.10.12.0
  - http-conduit ==2.3.8
  - text ==1.2.4.1
  - http-client ==0.7.9
  - aeson ==1.5.6.0
  - http-client-tls ==0.3.5.3
  - containers ==0.6.5.1

library:
  source-dirs: src

executables:
  htw-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - htw

tests:
  htw-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - htw
